"""
Data Quality Assurance for the German power market dataset.

Runs three layers of checks:
  1. Structural   — missingness, duplicates, temporal gaps
  2. Numerical    — outliers, sign checks, physical limits
  3. LLM-proposed — rules generated by the AI component at runtime

All outputs are written to outputs/qa_reports/.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from loguru import logger

REPORT_DIR = Path(__file__).resolve().parents[2] / "outputs" / "qa_reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Physical hard limits for German power market
HARD_LIMITS: dict[str, tuple[float, float]] = {
    "da_price":         (-500.0, 4_000.0),   # EUR/MWh (negative prices allowed)
    "wind_onshore_mw":  (0.0,    70_000.0),
    "wind_offshore_mw": (0.0,    10_000.0),
    "solar_mw":         (0.0,    80_000.0),
    "load_mw":          (15_000.0, 90_000.0),
}


# ── Structural checks ─────────────────────────────────────────────────────────

def check_missingness(df: pd.DataFrame) -> dict[str, Any]:
    total = len(df)
    result = {}
    for col in df.columns:
        n_missing = int(df[col].isna().sum())
        result[col] = {
            "n_missing": n_missing,
            "pct_missing": round(100 * n_missing / total, 2),
        }
    logger.info(f"Missingness check: {sum(v['n_missing'] for v in result.values())} total NaNs across {len(df.columns)} columns")
    return result


def check_duplicates(df: pd.DataFrame) -> dict[str, Any]:
    n_dup_idx = int(df.index.duplicated().sum())
    n_dup_rows = int(df.duplicated().sum())
    logger.info(f"Duplicates: {n_dup_idx} index duplicates, {n_dup_rows} row duplicates")
    return {"duplicate_index": n_dup_idx, "duplicate_rows": n_dup_rows}


def check_temporal_coverage(df: pd.DataFrame) -> dict[str, Any]:
    """Check for gaps larger than 1 hour in the timestamp index."""
    if not isinstance(df.index, pd.DatetimeIndex):
        return {"error": "Index is not DatetimeIndex"}
    diffs = df.index.to_series().diff().dt.total_seconds() / 3600
    gaps = diffs[diffs > 1.5]
    result = {
        "start": str(df.index.min()),
        "end": str(df.index.max()),
        "n_hours_expected": int((df.index.max() - df.index.min()).total_seconds() / 3600) + 1,
        "n_hours_actual": len(df),
        "n_gaps": len(gaps),
        "largest_gap_hours": float(gaps.max()) if len(gaps) > 0 else 0.0,
        "gap_timestamps": [str(t) for t in gaps.index[:10]],
    }
    logger.info(f"Temporal coverage: {result['n_hours_actual']}/{result['n_hours_expected']} hours, {result['n_gaps']} gaps")
    return result


# ── Numerical checks ──────────────────────────────────────────────────────────

def check_hard_limits(df: pd.DataFrame) -> dict[str, Any]:
    result = {}
    for col, (lo, hi) in HARD_LIMITS.items():
        if col not in df.columns:
            continue
        series = df[col].dropna()
        violations = series[(series < lo) | (series > hi)]
        result[col] = {
            "min": float(series.min()),
            "max": float(series.max()),
            "p5": float(series.quantile(0.05)),
            "p95": float(series.quantile(0.95)),
            "n_violations": len(violations),
            "violation_timestamps": [str(t) for t in violations.index[:5]],
        }
    return result


def check_outliers_iqr(df: pd.DataFrame, k: float = 4.0) -> dict[str, Any]:
    """Flag values beyond k * IQR from quartiles."""
    result = {}
    for col in df.select_dtypes(include=np.number).columns:
        series = df[col].dropna()
        q1, q3 = series.quantile(0.25), series.quantile(0.75)
        iqr = q3 - q1
        lo, hi = q1 - k * iqr, q3 + k * iqr
        outliers = series[(series < lo) | (series > hi)]
        result[col] = {
            "iqr_fence_low": round(lo, 2),
            "iqr_fence_high": round(hi, 2),
            "n_outliers": len(outliers),
        }
    return result


# ── LLM-proposed rules execution ──────────────────────────────────────────────

def execute_llm_rules(df: pd.DataFrame, rules: list[dict]) -> dict[str, Any]:
    """
    Execute validation rules proposed by the LLM.
    Each rule has: field, rule (description), condition (pandas expr), severity.
    """
    results = []
    for rule in rules:
        field = rule.get("field", "unknown")
        description = rule.get("rule", "")
        condition = rule.get("condition", "")
        severity = rule.get("severity", "warning")
        try:
            mask = eval(condition, {"df": df, "pd": pd, "np": np})  # noqa: S307
            n_valid = int(mask.sum()) if hasattr(mask, "sum") else int(mask)
            n_total = len(df)
            n_fail = n_total - n_valid
            results.append({
                "field": field,
                "rule": description,
                "severity": severity,
                "n_fail": n_fail,
                "pct_fail": round(100 * n_fail / n_total, 2),
                "passed": n_fail == 0,
                "condition": condition,
            })
        except Exception as exc:
            results.append({
                "field": field,
                "rule": description,
                "severity": severity,
                "error": str(exc),
                "passed": None,
            })
    return {"llm_rules": results}


# ── Full QA report ─────────────────────────────────────────────────────────────

def run_qa(
    df: pd.DataFrame,
    llm_rules: list[dict] | None = None,
    tag: str = "qa",
) -> dict[str, Any]:
    """Run all QA checks and save a JSON report."""
    report: dict[str, Any] = {
        "dataset_shape": {"rows": len(df), "cols": len(df.columns)},
        "columns": list(df.columns),
        "missingness": check_missingness(df),
        "duplicates": check_duplicates(df),
        "temporal_coverage": check_temporal_coverage(df),
        "hard_limits": check_hard_limits(df),
        "outliers_iqr": check_outliers_iqr(df),
    }
    if llm_rules:
        report["llm_rules"] = execute_llm_rules(df, llm_rules)

    out_path = REPORT_DIR / f"{tag}_report.json"
    with open(out_path, "w") as fh:
        json.dump(report, fh, indent=2, default=str)
    logger.success(f"QA report saved → {out_path}")
    return report


def summarise_qa(report: dict) -> str:
    """Return a plain-text summary of key QA findings."""
    lines = []
    miss = report.get("missingness", {})
    total_missing = sum(v.get("n_missing", 0) for v in miss.values())
    lines.append(f"Missing values:  {total_missing} total")

    dup = report.get("duplicates", {})
    lines.append(f"Duplicate rows:  {dup.get('duplicate_rows', 0)}")

    cov = report.get("temporal_coverage", {})
    lines.append(
        f"Temporal gaps:   {cov.get('n_gaps', 0)} gaps "
        f"(largest: {cov.get('largest_gap_hours', 0):.1f} h)"
    )

    limits = report.get("hard_limits", {})
    total_viol = sum(v.get("n_violations", 0) for v in limits.values())
    lines.append(f"Hard-limit violations: {total_viol}")

    llm_res = report.get("llm_rules", {}).get("llm_rules", [])
    if llm_res:
        failed = [r for r in llm_res if r.get("passed") is False]
        lines.append(f"LLM-rule failures: {len(failed)}/{len(llm_res)}")

    return "\n".join(lines)
